version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'bundler'
    directory: '/apps/server-monolith'
    schedule:
      interval: 'daily'
# npm dependencies are updated by the `upgrade_deps.yml` workflow
